# Generated by Django 3.1.3 on 2020-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201127_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
