# Generated by Django 3.1.3 on 2020-12-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, height_field=90, null=True, upload_to='covers', width_field=60),
        ),
    ]
