# Generated by Django 3.1.3 on 2020-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201208_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, default='Comments...', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='summary',
            field=models.TextField(default='We currently have no information on this authors work! Get in the comments and inform us!', max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='desc',
            field=models.TextField(default='Genre description', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
