# Generated by Django 3.1.3 on 2020-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201216_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, default='Comments...', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='minus',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='plus',
            field=models.BooleanField(),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'reviewer'), name='one_review_each'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('plus', 'minus'), name='bool_plus_minus'),
        ),
    ]
