# Generated by Django 3.1.3 on 2020-12-28 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20201227_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='one_review_each',
        ),
        migrations.RemoveConstraint(
            model_name='productreview',
            name='bool_plus_minus',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='minus',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='plus',
        ),
        migrations.AddField(
            model_name='productreview',
            name='score',
            field=models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')], default='UP', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='reviewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
